CFG="./t2v/configs/quant/W4A8_Timestep-aware_smooth/16x512x512.py" # the opensora config
Q_CFG="./t2v/configs/quant/W4A8_Timestep-aware_smooth/config.yaml" # the config of PTQ
CKPT_PATH="./logs/split_ckpt/OpenSora-v1-HQ-16x512x512-split.pth"  # splited ckpt generated by split_ckpt.py
OUTDIR="./logs/W4A8_Timestep-aware_smooth"  # your path to save the ptq result
CALIB_DATA_DIR="./logs/calib_data"  # your path of calib data
GPU_ID=$1  # your path to save generated videos

## ptq
CUDA_VISIBLE_DEVICES=$GPU_ID python t2v/scripts/ptq.py $CFG --outdir $OUTDIR \
	--calib_data $CALIB_DATA_DIR/calib_data.pt \
	--ptq_config $Q_CFG \
	--ckpt_path $CKPT_PATH \
	--part_fp \
	--precompute_text_embeds ./t2v/utils_files/text_embeds.pth
